version: '3'
services:
  web:
    build: .
    command: bash -c "if [ -f tmp/pids/server.pid ]; then rm tmp/pids/server.pid; fi && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST_NAME: mysql
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      RAILS_ENV: ${RAILS_ENV}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - .:/myapp
    ports:
      - "${RAILS_PORT}:3000"
    links:
      - mysql
      - redis
    tty: true
  mysql:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./mysql/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./mysql/data:/var/lib/mysql
      # mysqlのconfigファイルの設定
      - ./mysql/conf.d:/etc/mysql/conf.d
      # logファイル
      - ./mysql/log:/var/log/mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
       - ./redis:/data
    tty: true
